### ISSUE TITLE
Safe to use? Maintained?

### ISSUE THREAD

**Issue by DannyBen** [codekitchen/rubygems-s3#2]
Hi - is this still maintained, or at least safe to use at its current state?

The README said "I'm working to improve that" in the implementation notes and last commit was more than a year ago.

Really interested in this gem.

EDIT:

Or perhaps it is no longer needed, since the concept is merged into RubyGems?
https://github.com/rubygems/rubygems/pull/856

**Comment by codekitchen** [comment]
Yes this has been merged into rubygems itself, though the last time I checked it still wasn't supported by bundler. I'll update the README.
